import { z } from "zod";
import type { EmailMessage } from "@/lib/email";
import { escapeHtml, renderEmailLayout } from "@/lib/email";

// Single source of truth for the guest booking-request shape — reused by the
// API route (server) and the form island (client). Mirrors the conventions in
// src/lib/zagroda.ts (Polish messages, fieldErrorsFromZod for flattening).

export { fieldErrorsFromZod } from "@/lib/zagroda";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Group-type storage tokens (ASCII, mirroring booking_source/request_status
 * style). Human labels live in the presentation layer, mapped from these.
 */
export const GROUP_TYPE_VALUES = ["szkola", "przedszkole", "grupa_indywidualna", "inna"] as const;

export type GroupType = (typeof GROUP_TYPE_VALUES)[number];

/** Human labels for the group-type storage tokens (presentation layer). */
export const GROUP_TYPE_LABELS: Record<GroupType, string> = {
  szkola: "Szkoła",
  przedszkole: "Przedszkole",
  grupa_indywidualna: "Grupa indywidualna",
  inna: "Inna",
};

/** Strip the cosmetic separators a user may type in a phone number. */
export function normalizePhone(raw: string): string {
  return raw.replace(/[\s\-()]/g, "");
}

/**
 * Lenient PL mobile/landline check: an optional `+48` / `0048` / `48` country
 * prefix followed by exactly 9 national digits. Spacing/dashes/parens are
 * stripped first via normalizePhone.
 */
export function isValidPlPhone(raw: string): boolean {
  return /^(\+48|0048|48)?\d{9}$/.test(normalizePhone(raw));
}

/** True iff `raw` is a real calendar date in strict YYYY-MM-DD form. */
function isRealDate(raw: string): boolean {
  if (!DATE_RE.test(raw)) return false;
  const parsed = new Date(`${raw}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === raw;
}

/** True iff `raw` is a real date that is today or later (server-side authority). */
export function isTodayOrFuture(raw: string): boolean {
  if (!isRealDate(raw)) return false;
  const today = new Date().toISOString().slice(0, 10);
  return raw >= today;
}

export const bookingRequestSchema = z.object({
  zagroda_id: z.uuid("Nieprawidłowy identyfikator zagrody"),
  turnus_id: z.uuid("Wybierz turnus"),
  trip_date: z
    .string("Podaj datę")
    .regex(DATE_RE, "Podaj datę w formacie RRRR-MM-DD")
    .refine(isRealDate, "Nieprawidłowa data")
    .refine(isTodayOrFuture, "Data nie może być w przeszłości"),
  participants_count: z.coerce
    .number("Podaj liczbę uczestników")
    .int("Liczba uczestników musi być liczbą całkowitą")
    .min(1, "Co najmniej 1 uczestnik")
    .max(1000, "Maksymalnie 1000 uczestników"),
  group_type: z.enum(GROUP_TYPE_VALUES, "Wybierz typ grupy"),
  guest_name: z
    .string("Podaj imię i nazwisko")
    .trim()
    .min(1, "Podaj imię i nazwisko")
    .max(120, "Maksymalnie 120 znaków"),
  guest_email: z.email("Podaj prawidłowy adres e-mail"),
  guest_phone: z
    .string("Podaj numer telefonu")
    .trim()
    .min(1, "Podaj numer telefonu")
    .refine(isValidPlPhone, "Podaj prawidłowy numer telefonu (9 cyfr, opcjonalnie z +48)"),
});

export type BookingRequestInput = z.infer<typeof bookingRequestSchema>;

// S-08: owner-side payloads. Same client+server sharing contract as
// bookingRequestSchema; the SQL functions re-check ownership/date only as
// defense in depth.

export const manualBookingSchema = z.object({
  zagroda_id: z.uuid("Nieprawidłowy identyfikator zagrody"),
  turnus_id: z.uuid("Wybierz turnus"),
  trip_date: z
    .string("Podaj datę")
    .regex(DATE_RE, "Podaj datę w formacie RRRR-MM-DD")
    .refine(isRealDate, "Nieprawidłowa data")
    .refine(isTodayOrFuture, "Data nie może być w przeszłości"),
  participants_count: z.coerce
    .number("Podaj liczbę uczestników")
    .int("Liczba uczestników musi być liczbą całkowitą")
    .min(1, "Co najmniej 1 uczestnik")
    .max(1000, "Maksymalnie 1000 uczestników"),
  note: z.string().trim().max(500, "Maksymalnie 500 znaków").optional(),
});

export type ManualBookingInput = z.infer<typeof manualBookingSchema>;

export const dayBlockSchema = z.object({
  zagroda_id: z.uuid("Nieprawidłowy identyfikator zagrody"),
  blocked_date: z
    .string("Podaj datę")
    .regex(DATE_RE, "Podaj datę w formacie RRRR-MM-DD")
    .refine(isRealDate, "Nieprawidłowa data")
    .refine(isTodayOrFuture, "Data nie może być w przeszłości"),
});

export type DayBlockInput = z.infer<typeof dayBlockSchema>;

export interface BookingEmailContext {
  /** Site origin, e.g. `https://zagroda.example` — used to build the cancel link. */
  origin: string;
  /** Request id generated by the route (uuid) — builds the owner deep link. */
  requestId: string;
  /** Plaintext cancel token generated by the route (uuid). */
  cancelToken: string;
  zagrodaName: string;
  /** Owner recipient address; null when it could not be resolved (email skipped). */
  ownerEmail: string | null;
  /** Human-readable turnus label, when known. */
  turnusLabel: string | null;
  guest_name: string;
  guest_email: string;
  guest_phone: string;
  trip_date: string;
  participants_count: number;
  /** Group type chosen by the guest; null for legacy/untyped rows. */
  group_type: GroupType | null;
}

/**
 * Pure builder for the two transactional emails a submission triggers. Kept
 * pure (no IO) so it is unit-testable and so every guest-supplied field is
 * provably escaped before it lands in HTML. Returns `owner: null` when no
 * owner address was resolved.
 */
export function buildBookingEmails(ctx: BookingEmailContext): { guest: EmailMessage; owner: EmailMessage | null } {
  const name = escapeHtml(ctx.zagrodaName);
  const guestName = escapeHtml(ctx.guest_name);
  const guestEmail = escapeHtml(ctx.guest_email);
  const guestPhone = escapeHtml(ctx.guest_phone);
  const tripDate = escapeHtml(ctx.trip_date);
  const turnus = ctx.turnusLabel ? escapeHtml(ctx.turnusLabel) : null;
  const participants = ctx.participants_count;
  const cancelUrl = `${ctx.origin}/anuluj?token=${ctx.cancelToken}`;
  const cancelUrlHtml = escapeHtml(cancelUrl);

  const summaryRows = [
    `<li>Termin: <strong>${tripDate}</strong></li>`,
    turnus ? `<li>Turnus: <strong>${turnus}</strong></li>` : null,
    `<li>Liczba uczestników: <strong>${participants}</strong></li>`,
  ]
    .filter(Boolean)
    .join("");

  const guest: EmailMessage = {
    to: ctx.guest_email,
    subject: `Potwierdzenie zapytania — ${ctx.zagrodaName}`,
    html: renderEmailLayout({
      title: "Dziękujemy za zapytanie",
      bodyHtml: `<p>Dziękujemy za przesłanie zapytania o pobyt w zagrodzie <strong>${name}</strong>. Gospodarz skontaktuje się z Tobą wkrótce.</p>
<ul>${summaryRows}</ul>
<p>Jeśli chcesz anulować to zapytanie, kliknij poniższy link:</p>
<p><a href="${cancelUrlHtml}">${cancelUrlHtml}</a></p>`,
    }),
  };

  if (!ctx.ownerEmail) {
    return { guest, owner: null };
  }

  const requestUrl = `${ctx.origin}/dashboard/zapytania/${ctx.requestId}`;
  const requestUrlHtml = escapeHtml(requestUrl);

  // Owner-only: the request summary carries the group type. The guest email
  // (summaryRows above) is unchanged — the type surfaces only owner-side.
  const groupTypeLabel = ctx.group_type ? GROUP_TYPE_LABELS[ctx.group_type] : "—";
  const ownerSummaryRows = `${summaryRows}<li>Typ grupy: <strong>${escapeHtml(groupTypeLabel)}</strong></li>`;

  const owner: EmailMessage = {
    to: ctx.ownerEmail,
    replyTo: ctx.guest_email,
    subject: `Masz nowe zapytanie — ${ctx.zagrodaName}`,
    html: renderEmailLayout({
      title: "Nowe zapytanie o pobyt",
      bodyHtml: `<p>Otrzymałeś nowe zapytanie o pobyt w zagrodzie <strong>${name}</strong>.</p>
<ul>${ownerSummaryRows}</ul>
<p>Dane kontaktowe osoby kontaktowej:</p>
<ul>
<li>Imię i nazwisko: <strong>${guestName}</strong></li>
<li>E-mail: <strong>${guestEmail}</strong></li>
<li>Telefon: <strong>${guestPhone}</strong></li>
</ul>
<p><a href="${requestUrlHtml}">Zobacz zapytanie</a></p>
<p>Aby odpowiedzieć, użyj opcji „Odpowiedz” — wiadomość trafi bezpośrednio do osoby kontaktowej.</p>`,
    }),
  };

  return { guest, owner };
}

export interface DecisionEmailContext {
  guest_name: string;
  guest_email: string;
  zagroda_name: string;
  trip_date: string;
  turnus_label: string | null;
  participants_count: number;
}

function decisionSummaryRows(ctx: DecisionEmailContext): string {
  const turnus = ctx.turnus_label ? escapeHtml(ctx.turnus_label) : null;
  return [
    `<li>Termin: <strong>${escapeHtml(ctx.trip_date)}</strong></li>`,
    turnus ? `<li>Turnus: <strong>${turnus}</strong></li>` : null,
    `<li>Liczba uczestników: <strong>${ctx.participants_count}</strong></li>`,
  ]
    .filter(Boolean)
    .join("");
}

/**
 * Acceptance notification to the guest (FR-005). Final-state message: no
 * reply-to and no cancel link — the decision closes the request's lifecycle.
 */
export function buildAcceptanceEmail(ctx: DecisionEmailContext): EmailMessage {
  const name = escapeHtml(ctx.zagroda_name);
  const guestName = escapeHtml(ctx.guest_name);
  return {
    to: ctx.guest_email,
    subject: `Rezerwacja potwierdzona — ${ctx.zagroda_name}`,
    html: renderEmailLayout({
      title: "Rezerwacja potwierdzona",
      bodyHtml: `<p>Dzień dobry, ${guestName}!</p>
<p>Gospodarz zagrody <strong>${name}</strong> zaakceptował Twoje zapytanie o pobyt. Rezerwacja jest potwierdzona.</p>
<ul>${decisionSummaryRows(ctx)}</ul>
<p>Do zobaczenia w zagrodzie!</p>`,
    }),
  };
}

/**
 * Rejection notification to the guest. Same final-state posture as
 * buildAcceptanceEmail: no reply-to, no cancel link.
 */
export function buildRejectionEmail(ctx: DecisionEmailContext): EmailMessage {
  const name = escapeHtml(ctx.zagroda_name);
  const guestName = escapeHtml(ctx.guest_name);
  return {
    to: ctx.guest_email,
    subject: `Zapytanie odrzucone — ${ctx.zagroda_name}`,
    html: renderEmailLayout({
      title: "Zapytanie odrzucone",
      bodyHtml: `<p>Dzień dobry, ${guestName}.</p>
<p>Niestety gospodarz zagrody <strong>${name}</strong> odrzucił Twoje zapytanie o pobyt w wybranym terminie.</p>
<ul>${decisionSummaryRows(ctx)}</ul>
<p>Zachęcamy do wyszukania innej zagrody lub innego terminu w katalogu Zagroda Hub.</p>`,
    }),
  };
}

/**
 * Withdrawal notification to the guest (FR-016): the owner undid a previous
 * acceptance. Same final-state posture as the other decision emails: no
 * reply-to, no links.
 */
export function buildWithdrawalEmail(ctx: DecisionEmailContext): EmailMessage {
  const name = escapeHtml(ctx.zagroda_name);
  const guestName = escapeHtml(ctx.guest_name);
  return {
    to: ctx.guest_email,
    subject: `Rezerwacja wycofana — ${ctx.zagroda_name}`,
    html: renderEmailLayout({
      title: "Rezerwacja wycofana",
      bodyHtml: `<p>Dzień dobry, ${guestName}.</p>
<p>Gospodarz zagrody <strong>${name}</strong> wycofał wcześniej potwierdzoną rezerwację. Rezerwacja nie jest już aktualna.</p>
<ul>${decisionSummaryRows(ctx)}</ul>
<p>Zachęcamy do wyszukania innej zagrody lub innego terminu w katalogu Zagroda Hub.</p>`,
    }),
  };
}
