import { z } from "zod";
import type { EmailMessage } from "@/lib/email";
import { escapeHtml, renderEmailLayout } from "@/lib/email";

// Single source of truth for the guest booking-request shape — reused by the
// API route (server) and the form island (client). Mirrors the conventions in
// src/lib/zagroda.ts (Polish messages, fieldErrorsFromZod for flattening).

export { fieldErrorsFromZod } from "@/lib/zagroda";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/** Strip the cosmetic separators a user may type in a phone number. */
export function normalizePhone(raw: string): string {
  return raw.replace(/[\s\-()]/g, "");
}

/**
 * Lenient PL mobile/landline check: an optional `+48` / `0048` / `48` country
 * prefix followed by exactly 9 national digits. Spacing/dashes/parens are
 * stripped first via normalizePhone.
 */
export function isValidPlPhone(raw: string): boolean {
  return /^(\+48|0048|48)?\d{9}$/.test(normalizePhone(raw));
}

/** True iff `raw` is a real calendar date in strict YYYY-MM-DD form. */
function isRealDate(raw: string): boolean {
  if (!DATE_RE.test(raw)) return false;
  const parsed = new Date(`${raw}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === raw;
}

/** True iff `raw` is a real date that is today or later (server-side authority). */
export function isTodayOrFuture(raw: string): boolean {
  if (!isRealDate(raw)) return false;
  const today = new Date().toISOString().slice(0, 10);
  return raw >= today;
}

export const bookingRequestSchema = z.object({
  zagroda_id: z.uuid("Nieprawidłowy identyfikator zagrody"),
  turnus_id: z.uuid("Wybierz turnus"),
  trip_date: z
    .string("Podaj datę")
    .regex(DATE_RE, "Podaj datę w formacie RRRR-MM-DD")
    .refine(isRealDate, "Nieprawidłowa data")
    .refine(isTodayOrFuture, "Data nie może być w przeszłości"),
  participants_count: z.coerce
    .number("Podaj liczbę uczestników")
    .int("Liczba uczestników musi być liczbą całkowitą")
    .min(1, "Co najmniej 1 uczestnik")
    .max(1000, "Maksymalnie 1000 uczestników"),
  guest_name: z
    .string("Podaj imię i nazwisko")
    .trim()
    .min(1, "Podaj imię i nazwisko")
    .max(120, "Maksymalnie 120 znaków"),
  guest_email: z.email("Podaj prawidłowy adres e-mail"),
  guest_phone: z
    .string("Podaj numer telefonu")
    .trim()
    .min(1, "Podaj numer telefonu")
    .refine(isValidPlPhone, "Podaj prawidłowy numer telefonu (9 cyfr, opcjonalnie z +48)"),
});

export type BookingRequestInput = z.infer<typeof bookingRequestSchema>;

export interface BookingEmailContext {
  /** Site origin, e.g. `https://zagroda.example` — used to build the cancel link. */
  origin: string;
  /** Plaintext cancel token generated by the route (uuid). */
  cancelToken: string;
  zagrodaName: string;
  /** Owner recipient address; null when it could not be resolved (email skipped). */
  ownerEmail: string | null;
  /** Human-readable turnus label, when known. */
  turnusLabel: string | null;
  guest_name: string;
  guest_email: string;
  guest_phone: string;
  trip_date: string;
  participants_count: number;
}

/**
 * Pure builder for the two transactional emails a submission triggers. Kept
 * pure (no IO) so it is unit-testable and so every guest-supplied field is
 * provably escaped before it lands in HTML. Returns `owner: null` when no
 * owner address was resolved.
 */
export function buildBookingEmails(ctx: BookingEmailContext): { guest: EmailMessage; owner: EmailMessage | null } {
  const name = escapeHtml(ctx.zagrodaName);
  const guestName = escapeHtml(ctx.guest_name);
  const guestEmail = escapeHtml(ctx.guest_email);
  const guestPhone = escapeHtml(ctx.guest_phone);
  const tripDate = escapeHtml(ctx.trip_date);
  const turnus = ctx.turnusLabel ? escapeHtml(ctx.turnusLabel) : null;
  const participants = ctx.participants_count;
  const cancelUrl = `${ctx.origin}/anuluj?token=${ctx.cancelToken}`;
  const cancelUrlHtml = escapeHtml(cancelUrl);

  const summaryRows = [
    `<li>Termin: <strong>${tripDate}</strong></li>`,
    turnus ? `<li>Turnus: <strong>${turnus}</strong></li>` : null,
    `<li>Liczba uczestników: <strong>${participants}</strong></li>`,
  ]
    .filter(Boolean)
    .join("");

  const guest: EmailMessage = {
    to: ctx.guest_email,
    subject: `Potwierdzenie zapytania — ${ctx.zagrodaName}`,
    html: renderEmailLayout({
      title: "Dziękujemy za zapytanie",
      bodyHtml: `<p>Dziękujemy za przesłanie zapytania o pobyt w zagrodzie <strong>${name}</strong>. Gospodarz skontaktuje się z Tobą wkrótce.</p>
<ul>${summaryRows}</ul>
<p>Jeśli chcesz anulować to zapytanie, kliknij poniższy link:</p>
<p><a href="${cancelUrlHtml}">${cancelUrlHtml}</a></p>`,
    }),
  };

  if (!ctx.ownerEmail) {
    return { guest, owner: null };
  }

  const owner: EmailMessage = {
    to: ctx.ownerEmail,
    replyTo: ctx.guest_email,
    subject: `Masz nowe zapytanie — ${ctx.zagrodaName}`,
    html: renderEmailLayout({
      title: "Nowe zapytanie o pobyt",
      bodyHtml: `<p>Otrzymałeś nowe zapytanie o pobyt w zagrodzie <strong>${name}</strong>.</p>
<ul>${summaryRows}</ul>
<p>Dane kontaktowe nauczyciela:</p>
<ul>
<li>Imię i nazwisko: <strong>${guestName}</strong></li>
<li>E-mail: <strong>${guestEmail}</strong></li>
<li>Telefon: <strong>${guestPhone}</strong></li>
</ul>
<p>Aby odpowiedzieć, użyj opcji „Odpowiedz” — wiadomość trafi bezpośrednio do nauczyciela.</p>`,
    }),
  };

  return { guest, owner };
}
